# Generated by Django 2.2.2 on 2019-06-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('First_Name', models.CharField(max_length=15, null=True)),
                ('Last_Name', models.CharField(max_length=15)),
                ('Contact', models.IntegerField()),
                ('username', models.EmailField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15, null=True)),
                ('Re_Password', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
